package LeetCode;

/**
 * Created by aditi on 12/11/16.
 * Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.
 */
public class FindTheDifference {
    public static void main(String[] args) {

    }

    public char findDifference(String strA,String strB)
    {
        int lenA= 0;
        int lenB= 0;
        for(int i =0; i<strA.length();i++)
        {
            lenA+= (int)strA.charAt(i);
        }

        for (int k=0;k<strB.length();k++)
        {
            lenB+= (int) strB.charAt(k);
        }

        int diff = lenB-lenA;


        return (char) diff;

    }

}
